name: CI
# Triggers
on:
  workflow_dispatch: # Manual trigger from the Actions tab
jobs:
  ci:
    secrets: inherit
    uses: sisal-testorg/shared-workflows/.github/workflows/betnodeting-workflow.yaml@main
    with:
      project-type: "nodejs"
